version: '3.3'
services:
  dashboard-marcos:
    container_name: dashboard-marcos
    build: .
    command: npm run start:dev
    restart: always
    networks:
      - dashboard-network
    # ports:
    #   - "80:80"
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    environment:
      MODE_ENV: development

  mongo:
    image: mongo
    container_name: 'auteurnet-mongo'
    command: mongod --auth
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    restart: on-failure
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    networks:
      - dashboard-network


  webserver:
    image: nginx:mainline-alpine
    container_name: dashboardserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./dashboard:/var/www/html
      - .:/usr/src/app/src
      - ./nginx-conf/default.conf:/etc/nginx/conf.d/default.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - dashboard-marcos
      - mongo
    networks:
      - dashboard-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./dashboard:/var/www/html
      - .:/usr/src/app/src
      - dhparam:/etc/ssl/certs
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email ilse.lopez@mindsetmx.com --agree-tos --no-eff-email -d dashboard.marcosymarcos.mx

volumes:
  mongodb:
  certbot-etc:
  certbot-var:
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/dashboard-marcos/dhparam/
      o: bind


networks:
  dashboard-network:
    driver: bridge
